apiVersion: autopilot.k0sproject.io/v1beta2
kind: UpdateConfig
metadata:
  name: example
  namespace: default
spec:
  channel: edge_release
  updateServer: https://docs.k0sproject.io/
  upgradeStrategy:
    cron: "0 12 * * TUE,WED" # Check for updates at 12:00 on Tuesday and Wednesday.

  planSpec: # the needed bits to be able to create the actual Plan object
    command: update
    targets:
      controllers:
        discovery:
          selector:
      workers:
        discovery:
          selector:
